# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  topperservice:
    image: topperservice
    build:
      context: .
      dockerfile: TopperService/Dockerfile
    ports:
      - 80
